### ISSUE TITLE
SP Football 23 on Steam Deck

### ISSUE THREAD

**Issue by jtran8302** [pes-modding/sider7#5]
Love the latest version for what it tries to approach, but I am playing SP Football 23 at the moment and it looks like the patcher.exe is looking for the PES2021.exe, hence it fails to implement?

**Comment by juce** [comment]
fair point. In the next release, I'll add a flag to patcher so that it will be possible specify a different filename. Like this:
```
patcher.exe --file ..\SomeOther.exe
```

**Comment by juce** [comment]
Actually, i forgot that it is already possible. If you run patcher with `--help` flag, it will show how to do it.
Basically, you just specify the path to your exe file, like this:
```
patcher.exe ..\..\whatever\path\to\your\other\exe.file
```

**Comment by juce** [comment]
already implemented
