### ISSUE TITLE
sider.dll 7.2.1 does not run with sider.exe 7.1.7

### ISSUE THREAD

**Issue by 3v1n0** [pes-modding/sider7#7]
I've downloaded the [v7.2.1 Special Edition Update](https://github.com/pes-modding/sider7/releases/tag/v7.2.1) release .dll but it does not run in wine when using the old exe, while the archive is missing the new exe file.

**Comment by juce** [comment]
exe isn't included, because 7.2.1 works without sider.exe.
Use patcher.exe instead to "attach" sider.dll to PES2021.exe

**Comment by juce** [comment]
closing, as not really an issue.
